# Site
title:              Griffin Foster
bio:                'Searching for intelligence and life beyond Earth.'
description:        "Radio astronomy and signal processing researcher based at the University of Oxford."
reading_time:       false
words_per_minute:   200
logo:               'assets/img/head_logo.png'
background:         'assets/img/llandudno.jpg'
locale:             en_GB
url:                https://griffinfoster.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              griffin.foster@gmail.com
twitter:            griffinfoster
#facebook:           username
github:             griffinfoster
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           griffinfoster
#xing:              username
#instagram:          username
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
